micronaut:
  application:
    name: pixproject
  session:
    http:
      cookie: true
      header: true
datasources:
  default:
    url: jdbc:mysql://localhost:3306/desafiopix?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: darthluck10
    schema-generate: CREATE_DROP
    dialect: MYSQL
